# Generated by Django 5.1.1 on 2024-10-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_shopregistration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopregistration',
            name='area',
            field=models.TextField(max_length=100),
        ),
    ]
