# Generated by Django 5.1.1 on 2024-10-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_alter_shopregistration_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopregistration',
            name='isActive',
            field=models.BooleanField(default=False),
        ),
    ]
