# Generated by Django 5.1.1 on 2024-10-26 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0006_alter_shopregistration_isactive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shopregistration',
            name='user',
        ),
    ]
