# Generated by Django 5.1.1 on 2024-10-25 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_alter_customuser_groups_alter_customuser_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='isSeller',
            field=models.BooleanField(default=False),
        ),
    ]
